filter:
  paths:
    - src/*
    - tests/*

build:
  nodes:
    tests:
      tests:
        override:
          - true
    analysis:
      tests:
        override:
          - php-scrutinizer-run
tools:
  external_code_coverage:
    timeout: 600
